name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check current Java version
        id: java-check
        run: |
            java --version | head -n 1
            echo "CURRENT_JAVA=$(java --version | head -n 1 | grep -co ' 17\.')" >> $GITHUB_ENV

      - name: Set up JDK 17
        if: env.CURRENT_JAVA != '1'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            --no-daemon --warning-mode=none \
            -x lint -x test

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: pio/build/outputs/apk/*/release/*.apk

  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check current Java version
        id: java-check
        run: |
            java --version | head -n 1
            echo "CURRENT_JAVA=$(java --version | head -n 1 | grep -co ' 17\.')" >> $GITHUB_ENV


      - name: Set up JDK 17
        if: env.CURRENT_JAVA != '1'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug \
            --no-daemon --warning-mode=none \
            -x lint -x test

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: pio/build/outputs/apk/*/debug/*.apk